#!/bin/bash
#
#Universidad Simón Bolívar
#Traductores e Interpretadores - CI3715
#Manuel Gomes - 11-10375
#Ricardo Vethencourt - 09-10894
#Script para ejecutar el proyecto
#$1 es el archivo de entrada que se pasa como parámetro
#para analizar.

python3 main.py $1